### ISSUE TITLE
cannot use output path -O

### ISSUE THREAD

**Issue by earthcolor** [rainforestnet/CrystalReportsNinja#1]
Hi, first , let me say I am so happy to see this project alive again! I use the old version for scheduled reports, and it works great.
I'm testing this version, and it seems I can't specify an output path and filename. The output file is always  placed next to the report file, and if I do specify an output location with -O, the output files has no extension and isplaced next to the report file. It is the correct format, as i can open it, but the extension is missing and is always named as the default name, not what i specify on the command line.

Kudos for updating this project, I hope you can make an easy fix for this issue.

thanks!

**Comment by ashoct28** [comment]
I got the same problem as above. -O option is not working as intended. Please fix. Thanks in advance.

**Comment by satyamk2k** [comment]
Thank you for the update, yes -O option not working and file extension not generating. but the content is writing in the format which we specified but the file extension and out put path not working, File is always writing into the report folder.

**Comment by catr213** [comment]
I am interested in the fix for the -O option as well.  I hope that it is in the works!  Thank You!

**Comment by jdybala** [comment]
-O not working for me either.

**Comment by Mamamouchi** [comment]
You just have to recompile the source with VS and the option -O will work fine.

**Comment by rainforestnet** [comment]
@Mamamouchi  was right. I have just re-compiled and updated. Please download it here.
https://github.com/rainforestnet/CrystalReportsNinja/blob/master/Deployment/CrystalReportsNinja.exe
