### ISSUE TITLE
Parameters in selection formula

### ISSUE THREAD

**Issue by mcdado** [rainforestnet/CrystalReportsNinja#21]
Premise: I'm a CR newbie, I have inherited a project using it and I'm trying to automate generating pdf reports.

I have a report that has this _selection formula_: `{RPT_lavoro.session}={@Sessione}` with `RPT_lavoro` being a database table, `session` being a field, and `@Sessione` from what I understand is a parameter. The software using CR passes that value and uses this formula to filter the tables. I'm trying something like this:

```
CrystalReportsNinja.exe -E pdf -F report.rpt -O test.pdf -a "Sessione:18"
```

With these results:

```
Report loaded successfully
Database Login done
Completed
```

And the pdf is generated, but it's empty. I tried removing or editing by hand the formula, and it works. I just cannot understand how to make it work. Any tips?

**Comment by sunk818** [comment]
does -l (log) produce anything useful?

**Comment by mcdado** [comment]
Actually it makes no difference, no extra output or changes

**Comment by mcdado** [comment]
So… remember that I'm a newbie?

`@Sessione` is a formula field. How I specify an external parameter for my reports?
