### ISSUE TITLE
Exception raised

### ISSUE THREAD

**Issue by neo2011** [rainforestnet/CrystalReportsNinja#3]
Hi All,

Can anyone come to my rescue please?

I ran the following commands;

CrystalReportsNinja.exe -F SM_AO_Invoice.rpt -O AOInvoice -E pdf

and the following messages and exception was raised;

Report loaded successfully
Database Login done
Exception: Unable to cast COM object of type 'CrystalDecisions.ReportAppServer.C
ontrollers.ReportSourceClass' to interface type 'CrystalDecisions.ReportAppServe
r.Controllers.ISCRReportSource'. This operation failed because the QueryInterfac
e call on the COM component for the interface with IID '{98CDE168-C1BF-4179-BE4C
-F2CFA7CB8398}' failed due to the following error: No such interface supported (
Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
Inner Exception:

Please what am I doing wrong?

**Comment by rainforestnet** [comment]
@neo2011 
I am not sure the following link helps
https://answers.sap.com/questions/304272/upgrade-to-sp-21-unable-to-cast-to-interface-type.html

**Comment by rainforestnet** [comment]
welcome @neo2011
