### ISSUE TITLE
"CrystalReportsNinja.exe removed"  Erm, is it coming back soon ?

### ISSUE THREAD

**Issue by bushy555** [rainforestnet/CrystalReportsNinja#31]

**Comment by jan-sp** [comment]
Can't find the CrystalReportsNinja.exe on the site neither... When would it be back please?

Kind regards,
Jan

**Comment by fogoat** [comment]
Go here: https://github.com/rainforestnet/CrystalReportsNinja/blob/032aef5508a524deaad8c53f923bc6dc925f7085/Deployment/CrystalReportsNinja.exe

Click Download

![image](https://user-images.githubusercontent.com/6989799/46489981-9bb5e100-c7bb-11e8-852a-0f68b7493b94.png)
