### ISSUE TITLE
Problem connection with database connection

### ISSUE THREAD

**Issue by Mamamouchi** [rainforestnet/CrystalReportsNinja#4]
Hi, let me say that your project works great and your source are very clear.
However, I've got an error with all the reports with a connection to a database. I've got the following message:
Failed to load database information.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
I've search within the documentation of SAP and changed the version of Crystal but the problem remains the same.

Thanks in advance

**Comment by rainforestnet** [comment]
@Mamamouchi I don't quite understand your problem. Did you mean that it doesn't work for one particular database and it works for the rest?

**Comment by Mamamouchi** [comment]
@rainforestnet I'm so sorry, it was a mistake. In fact, my report was parameterized to use a JDBC driver...
