### ISSUE TITLE
Invalid crystal reports file

### ISSUE THREAD

**Issue by icemastr** [rainforestnet/CrystalReportsNinja#53]
I have used Crystal Reports Ninja to print a few reports to PDF. I have a Crystal Report that is an invoice, the original template came with our ERP software and it is fairly complex so recreating it from scratch would be a lot of work. When I try to use Crystal Reports Ninja to save to PDF it gives this error: 
Exception: Invalid Crystal Reports file
Inner Exception:

I have compared a similar invoice report that does work and I do not see any major differences in how things are setup. Are there some settings that might cause this issue that I should check or is there a way to get more detail about why this report is not working?

**Comment by icemastr** [comment]
Well in Crystal Reports I exported the report to a rpt file instead of just saving it as an rpt file and then it worked. I also had to use this other for of Crystal Reports Ninja. https://github.com/mhertzfeld/CrystalReportsNinja

**Comment by fogoat** [comment]
Did you save data to the report? I believe it is under File in the Crystal Report desktop software. I think you need to have it turned off.

**Comment by icemastr** [comment]
No I did not have the save data to report option enabled.
